change to colorScheme = NULL fixing #33
swsoyee/r3dmol pull request #34
Opened 2021-05-14 07:34 UTC by BradyAJohnston

Fixes error with colorScheme = "default" that overrides user-specified colours.

Fixes bug raised in #33.

2021-05-14 08:25 UTC, swsoyee requested changes
It would be better to add the fix to NEWS.md
https://github.com/swsoyee/r3dmol/blob/master/NEWS.md

I will release the v0.1.3 to CRAN if there are not other fixes recently.

2021-05-14 08:25 UTC, swsoyee commented on R/style.R
> +                         colorScheme = NULL,
How about also fix the documentations about `colorScheme`?

```
#' @param colorScheme Specify scheme to color the atoms by. Default is
#' "default". Other choies are "Carbon", ssPyMOL", "ssJmol", "Jmol",
#' "default", "amino",
#' "shapely", "nucleic", "chain", "chainHetatm", "prop".
```

- Maybe there is a typo in `choies`?
- A quotation is missing before `ssPyMOL`

2021-05-14 12:36 UTC, swsoyee approved these changes
Since the PR is LGTM, but I am very sorry for taking the liberty of fixing some typos in the documentation. I'll be able to merge it when the check passes. Thanks a lot for fixing this bug!

2021-05-14 15:45 UTC, merged

2021-05-15 05:16 UTC, BradyAJohnston commented
Thanks for fixing the minor stuff - it seems that I was having trouble with generating the documentation etc for some reason. Thanks for the fix and thanks for the merge!